<a href="https://colab.research.google.com/github/Adarsh230305/Data_Science/blob/main/Iiris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [8]:
df=sns.load_dataset('iris')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [10]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [13]:
from sklearn.model_selection import train_test_split
X = df.drop("species",axis=1)
y=df["species"]
X_train, X_test, y_train, y_test=train_test_split(X, y,test_size=0.2,random_state=42)
x_train_scaled=scaler.fit_transform(X_train)
x_test_scaled=scaler.fit_transform(X_test)

In [14]:
from sklearn.svm import SVC
model_svm=SVC()
model_svm.fit(x_train_scaled,y_train)
y_pred=model_svm.predict(x_test_scaled)

In [15]:
y_pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'versicolor', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa'], dtype=object)

## GridSearchCV

In [16]:
from sklearn.model_selection import GridSearchCV
parameter={
    'kernel':("linear","rbf","sigmoid’"),
   "C":[1,10],
    "gamma":['scale'],

}
clf=GridSearchCV(model_svm,parameter,cv=5,)
clf.fit(x_train_scaled,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10], 'gamma': ['scale'],
                         'kernel': ('linear', 'rbf', 'sigmoid’')})

In [17]:
model_df=pd.DataFrame(clf.cv_results_)
model_df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003194,0.001797,0.001627,0.000178,1,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",0.958333,1.000000,0.833333,1.0,0.958333,0.950000,0.061237,2
1,0.002352,0.000113,0.001543,0.000084,1,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",0.958333,1.000000,0.833333,1.0,0.958333,0.950000,0.061237,2
2,0.000788,0.000038,0.000000,0.000000,1,scale,sigmoid’,"{'C': 1, 'gamma': 'scale', 'kernel': 'sigmoid’'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,0.002242,0.000115,0.001584,0.000103,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.958333,1.000000,0.833333,1.0,1.000000,0.958333,0.064550,1
4,0.007458,0.001826,0.005134,0.001589,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.958333,0.958333,0.833333,1.0,0.958333,0.941667,0.056519,4
5,0.001730,0.001017,0.000000,0.000000,10,scale,sigmoid’,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid’'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5

In [18]:
model_df['mean_score_time']

0    0.001627
1    0.001543
2    0.000000
3    0.001584
4    0.005134
5    0.000000
Name: mean_score_time, dtype: float64

## RandomizedSearchCV

In [19]:
from sklearn.model_selection import RandomizedSearchCV
clf1=RandomizedSearchCV(model_svm,parameter,n_iter=10,cv=5)
clf1.fit(x_train_scaled,y_train)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 10], 'gamma': ['scale'],
                                        'kernel': ('linear', 'rbf',
                                                   'sigmoid’')})

In [20]:
model_df1=pd.DataFrame(clf1.cv_results_)
model_df1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_gamma,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002518,0.000349,0.001557,0.000038,linear,scale,1,"{'kernel': 'linear', 'gamma': 'scale', 'C': 1}",0.958333,1.000000,0.833333,1.0,0.958333,0.950000,0.061237,2
1,0.002507,0.000041,0.001662,0.000127,rbf,scale,1,"{'kernel': 'rbf', 'gamma': 'scale', 'C': 1}",0.958333,1.000000,0.833333,1.0,0.958333,0.950000,0.061237,2
2,0.000804,0.000037,0.000000,0.000000,sigmoid’,scale,1,"{'kernel': 'sigmoid’', 'gamma': 'scale', 'C': 1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,0.002114,0.000076,0.001441,0.000054,linear,scale,10,"{'kernel': 'linear', 'gamma': 'scale', 'C': 10}",0.958333,1.000000,0.833333,1.0,1.000000,0.958333,0.064550,1
4,0.002184,0.000051,0.001416,0.000054,rbf,scale,10,"{'kernel': 'rbf', 'gamma': 'scale', 'C': 10}",0.958333,0.958333,0.833333,1.0,0.958333,0.941667,0.056519,4
5,0.000847,0.000115,0.000000,0.000000,sigmoid’,scale,10,"{'kernel': 'sigmoid’', 'gamma': 'scale', 'C': 10}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5

#Ensemble Learning

##Stacking

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import StackingClassifier

In [22]:
df=sns.load_dataset('iris')

In [23]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [24]:
X=df.drop("species",axis=1)
Y=df["species"]

In [25]:
le=LabelEncoder()
y_encoded=le.fit_transform(Y)

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y_encoded, test_size=0.33, random_state=42)

In [27]:
base_models=[
    ("LogisticRegression",LogisticRegression(max_iter=1000)),
    ("DecisionTree",DecisionTreeClassifier(random_state=42)),
   ( "KNN",KNeighborsClassifier(n_neighbors=5))
]

In [28]:
meta_model=SVC(probability=True,kernel='rbf',random_state=42)

In [29]:
stacking_clf=StackingClassifier(
    estimators=base_models,
    final_estimator=meta_model,
    cv=5
)

In [30]:
stacking_clf.fit(X_train,y_train)

StackingClassifier(cv=5,
                   estimators=[('LogisticRegression',
                                LogisticRegression(max_iter=1000)),
                               ('DecisionTree',
                                DecisionTreeClassifier(random_state=42)),
                               ('KNN', KNeighborsClassifier())],
                   final_estimator=SVC(probability=True, random_state=42))

In [31]:
y_pred=stacking_clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.98

## Bagging

### RandomForest

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
RF_clf=RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
     max_features='sqrt',
)

In [34]:
RF_clf.fit(X_train,y_train)

RandomForestClassifier()

In [35]:
y_pred=RF_clf.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.98

##Boosting

### AdaBoost

In [36]:
from sklearn.ensemble import AdaBoostClassifier

In [37]:
AB_model= AdaBoostClassifier(n_estimators=50, learning_rate=1.0)

In [38]:
AB_model.fit(X_train,y_train)

AdaBoostClassifier()

In [40]:
y_pred=AB_model.predict(X_test)

In [42]:
accuracy=accuracy_score(y_pred,y_test)
accuracy

0.92

###Gradient Boosting

In [43]:
from sklearn.ensemble import GradientBoostingClassifier

In [44]:
GB_model=GradientBoostingClassifier(learning_rate=0.1, n_estimators=100)

In [45]:
GB_model.fit(X_train,y_train)

GradientBoostingClassifier()

In [46]:
y_pred=GB_model.predict(X_test)

In [47]:
accuracy=accuracy_score(y_pred,y_test)
accuracy

0.98

###XGBoosting

In [56]:
import xgboost as xgb

In [57]:
XG_model=xgb.XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, use_label_encoder=False, eval_metric='mlogloss', random_state=42)

In [58]:
XG_model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [60]:
y_pred=XG_model.predict(X_test)

In [62]:
accuracy=accuracy_score(y_pred,y_test)
accuracy

0.98