<a href="https://colab.research.google.com/github/Adarsh230305/Data_Science/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

In [ ]:
import numpy as np
import pandas as pd

## Series
##### A series is one  dimensional labeled array capable of holding any data type ,the axis labels are collectively called the index

In [ ]:
my_labels=["a","b","c"]
my_list=[10,20,30]
my_array=np.array([20,30,40])
my_dic={"x":5,"y":10,"z":15}
print("List: \n",pd.Series((my_list)))
print("With custom labels")
print('List with custom label:\n',pd.Series(my_list,index=my_labels))
print('array with custom label:\n',pd.Series(my_array,index=my_labels))
print('dictionary:\n',pd.Series(my_dic))

List:
 0    10
1    20
2    30
dtype: int64
With custom labels
List with custom label:
 a    10
b    20
c    30
dtype: int64
array with custom label:
 a    20
b    30
c    40
dtype: int64
dictionary:
 x     5
y    10
z    15
dtype: int64

## Data Frame
#### Collection of multiple series

#### Creating a DataFrame

In [ ]:
# From dictionary
My_data={
    "name":["Adarsh","muni","sumit","rohit"],
    "age":[21,21,20,22],
    "cgpa":[8.84,9.3,8.5,8.1]
}
df1=pd.DataFrame(My_data)
print(df1)

     name  age  cgpa
0  Adarsh   21  8.84
1    muni   21  9.30
2   sumit   20  8.50
3   rohit   22  8.10

In [ ]:
# From list
data_list=[
    ['Adarsh',21,"NY",8500],
    ['Muni',21,"WD",7500],
    ['Sumit',20,'LD',6580],
    ['Rohit',22,'RNC',7894]
    ]
df2=pd.DataFrame(data_list,columns=["Name","Age","City","Salary"])
print(df2)

     Name  Age City  Salary
0  Adarsh   21   NY    8500
1    Muni   21   WD    7500
2   Sumit   20   LD    6580
3   Rohit   22  RNC    7894

### Selection and Indexing of column

In [ ]:
print(df2)
print('\n')
print(df2["Name"]) # single Column
print(df2[["Name","Age"]]) # Multiple column

     Name  Age City  Salary
0  Adarsh   21   NY    8500
1    Muni   21   WD    7500
2   Sumit   20   LD    6580
3   Rohit   22  RNC    7894


0    Adarsh
1      Muni
2     Sumit
3     Rohit
Name: Name, dtype: object
     Name  Age
0  Adarsh   21
1    Muni   21
2   Sumit   20
3   Rohit   22

### Creating a new Column

In [ ]:
print(df2)
print("\n")
df2["Skill"]=["DSA","WEB","DSA","ML"]
print("New column Created\n",df2)

     Name  Age City  Salary
0  Adarsh   21   NY    8500
1    Muni   21   WD    7500
2   Sumit   20   LD    6580
3   Rohit   22  RNC    7894


New column Created
      Name  Age City  Salary Skill
0  Adarsh   21   NY    8500   DSA
1    Muni   21   WD    7500   WEB
2   Sumit   20   LD    6580   DSA
3   Rohit   22  RNC    7894    ML

### Removing a column

In [ ]:
print(df2)
print("\n")
print("dropped but not removed\n",df2.drop("Skill",axis=1)) # it will just drop the column but actually not remove it
print("\n")
# to remove the column use inplace=True
df2.drop("Skill",axis=1,inplace=True)
print(df2)

     Name  Age City  Salary Skill
0  Adarsh   21   NY    8500   DSA
1    Muni   21   WD    7500   WEB
2   Sumit   20   LD    6580   DSA
3   Rohit   22  RNC    7894    ML


dropped but not removed
      Name  Age City  Salary
0  Adarsh   21   NY    8500
1    Muni   21   WD    7500
2   Sumit   20   LD    6580
3   Rohit   22  RNC    7894


     Name  Age City  Salary
0  Adarsh   21   NY    8500
1    Muni   21   WD    7500
2   Sumit   20   LD    6580
3   Rohit   22  RNC    7894

### Selecting Rows

In [ ]:
print(df2)
print(df2.loc[2]) # single row
print('\n')
print(df2.loc[[0,1]]) # multiple row
print('\n')
df2.iloc[3] # using indexing

     Name  Age City  Salary
0  Adarsh   21   NY    8500
1    Muni   21   WD    7500
2   Sumit   20   LD    6580
3   Rohit   22  RNC    7894
Name      Sumit
Age          20
City         LD
Salary     6580
Name: 2, dtype: object


     Name  Age City  Salary
0  Adarsh   21   NY    8500
1    Muni   21   WD    7500

Name      Rohit
Age          22
City        RNC
Salary     7894
Name: 3, dtype: object

In [ ]:
### Selecting Subset of Rows & Columns

In [ ]:
print(df2)
print('\n')
df2.loc[[0,1]][["Name","Age"]]

     Name  Age City  Salary
0  Adarsh   21   NY    8500
1    Muni   21   WD    7500
2   Sumit   20   LD    6580
3   Rohit   22  RNC    7894

     Name  Age
0  Adarsh   21
1    Muni   21

### Conditional Selection

In [ ]:
print(df2)
print('\n')
df2[df2['Age']>=21]

     Name  Age City  Salary
0  Adarsh   21   NY    8500
1    Muni   21   WD    7500
2   Sumit   20   LD    6580
3   Rohit   22  RNC    7894

     Name  Age City  Salary
0  Adarsh   21   NY    8500
1    Muni   21   WD    7500
3   Rohit   22  RNC    7894

In [ ]:
df2[(df2['Age']>=21) &  (df2['City']=="NY")]

     Name  Age City  Salary
0  Adarsh   21   NY    8500

### Missing Data

### Finding Missing Data

In [ ]:
data={
    'A':[1,2,3,np.nan],
    'B':[1,np.nan,np.nan,2],
    'C':[1,np.nan,np.nan,np.nan],
    'D':[1,2,3,4]
}
df=pd.DataFrame(data)
print(df)
print('\n')
print(df.isna())
print('\n')
print(df.isna().sum()) # Count the no.of null values in each row
print(df.isna().any()) # tell whether atleat a null is present in row or not

     A    B    C  D
0  1.0  1.0  1.0  1
1  2.0  NaN  NaN  2
2  3.0  NaN  NaN  3
3  NaN  2.0  NaN  4


       A      B      C      D
0  False  False  False  False
1  False   True   True  False
2  False   True   True  False
3   True  False   True  False


A    1
B    2
C    3
D    0
dtype: int64
A     True
B     True
C     True
D    False
dtype: bool

### Removing Missing Data

In [ ]:
print(df)
print('\n')
print(df.dropna()) # it will just drop row which has nan,not remove from origanal data
print('\n')
df

     A    B    C  D
0  1.0  1.0  1.0  1
1  2.0  NaN  NaN  2
2  3.0  NaN  NaN  3
3  NaN  2.0  NaN  4


     A    B    C  D
0  1.0  1.0  1.0  1

     A    B    C  D
0  1.0  1.0  1.0  1
1  2.0  NaN  NaN  2
2  3.0  NaN  NaN  3
3  NaN  2.0  NaN  4

In [ ]:
print(df.dropna(thresh=2)) # thresh =2 means row with 2 atleast non-null value

     A    B    C  D
0  1.0  1.0  1.0  1
1  2.0  NaN  NaN  2
2  3.0  NaN  NaN  3
3  NaN  2.0  NaN  4

### Filling Missing Data
(when we write inplace=True they only
the orignal Data Frame gets,change both in fillna() ,dropna())

In [ ]:
# fillna() is used to fill data in column wise
print(df)

print(df.fillna(0)) # replace nan with zeros
print('\n')
values={
    'A':10,
    'B':20,
    'C':30,
    'D':40
}
print(df.fillna(value=values)) # fill null the particular values
print('\n')
print(df.fillna(df.mean())) # fill null with mean of that column

     A    B    C  D
0  1.0  1.0  1.0  1
1  2.0  NaN  NaN  2
2  3.0  NaN  NaN  3
3  NaN  2.0  NaN  4
     A    B    C  D
0  1.0  1.0  1.0  1
1  2.0  0.0  0.0  2
2  3.0  0.0  0.0  3
3  0.0  2.0  0.0  4


      A     B     C  D
0   1.0   1.0   1.0  1
1   2.0  20.0  30.0  2
2   3.0  20.0  30.0  3
3  10.0   2.0  30.0  4


     A    B    C  D
0  1.0  1.0  1.0  1
1  2.0  1.5  1.0  2
2  3.0  1.5  1.0  3
3  2.0  2.0  1.0  4

### Merging two dataframes
(there should be a comman thing in both df to merge)

In [ ]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})
# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})
print(employees)
print('\n')
print(salaries)

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR


   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
pd.merge(employees,salaries,on="employee_id",how="inner") # inner merge on basis of employees ,no null value will be there

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on="employee_id",how="outer") # outer merge on basis of employees ,null value will be there

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees,salaries,on="employee_id",how="left") # left merge on basis of employees ,null value will be there

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees,salaries,on="employee_id",how="right") # right merge on basis of salaries,null value will be there

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

### concatination of two dataFrame

In [ ]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})
df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})
print(df1)
print('\n')
print(df2)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2


    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2]) # by default axis =0(row axis)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2],axis=1) # column wise concatination

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
pd.concat([df2,df1],axis=1) # column wise concatination

    A   B   C   A   B   C
0  A3  B3  C3  A0  B0  C0
1  A4  B4  C4  A1  B1  C1
2  A5  B5  C5  A2  B2  C2

### joining 2 data Frame

In [ ]:

df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [ ]:
print(df1)
print('\n')
print(df2)

      name
1    Alice
2      Bob
3  Charlie


   score
2     85
3     90
4     75

In [ ]:
df1.join(df2,how="inner") # inner join ,jo chiz comman hoga sirf unhi k values join  honge

      name  score
2      Bob     85
3  Charlie     90

In [ ]:
df1.join(df2,how="outer")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

### Group by

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
df.groupby('Category')['Sales'].sum() # make a group on basis of category and find the sum of sales

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
# Group by store and calculate the sum of sales
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
# mutiple group by
print(df.groupby(['Category','Store'])['Sales'].sum())
print('\n',df.groupby(['Store','Category'])['Sales'].sum())

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

 Store  Category
S1     A           220
       B           500
S2     A           350
       B           430
Name: Sales, dtype: int64

### Aggregation

In [ ]:
df['Sales'].mean()
# simlarly do for (sum,min,max,count,std,median)

np.float64(187.5)

In [ ]:
# use of agg function
df['Sales'].agg(['sum','mean','median','std','min','max'])

sum       1500.000000
mean       187.500000
median     190.000000
std         66.062741
min        100.000000
max        300.000000
Name: Sales, dtype: float64

### Pivot table

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    615     54   John  January      Q1
1  2023-01-02       B   West    299     29   Mary  January      Q1
2  2023-01-03       C  North    867     92    Bob  January      Q1
3  2023-01-04       D  South    265     51  Alice  January      Q1
4  2023-01-05       A   East    644     95   John  January      Q1
5  2023-01-06       B   West    400     96   Mary  January      Q1
6  2023-01-07       C  North    657     35    Bob  January      Q1
7  2023-01-08       D  South    704     54  Alice  January      Q1
8  2023-01-09       A   East    824     10   John  January      Q1
9  2023-01-10       B   West    443     24   Mary  January      Q1
10 2023-01-11       C  North    278     66    Bob  January      Q1
11 2023-01-12       D  South    334     69  Alice  January      Q1
12 2023-01-13       A   East    923     83   John  January      Q1
13 2023-01-14       B   West    468     25   Mary  January      Q1
14 2023-01-15       C  North    806     33    Bob  January      Q1
15 2023-01-16       D  South    185     69  Alice  January      Q1
16 2023-01-17       A   East    977     43   John  January      Q1
17 2023-01-18       B   West    389     47   Mary  January      Q1
18 2023-01-19       C  North    562     30    Bob  January      Q1
19 2023-01-20       D  South    399     45  Alice  January      Q1

In [ ]:
pd.pivot_table(df,values='Sales',index='Product',columns='Region',aggfunc='median') # by default aggfunc is mean,but here we change it to mean
# note since we are using aggeration here,we need to provide numeric values in "values"

Region    East  North  South   West
Product
A        824.0    NaN    NaN    NaN
B          NaN    NaN    NaN  400.0
C          NaN  657.0    NaN    NaN
D          NaN    NaN  334.0    NaN

### Cross Tab

In [ ]:
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

### Operations

In [ ]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
print("Shape: ",df1.shape)
print("columns: ",df1.columns)
print("Index: ",df1.index)

Shape:  (5, 3)
columns:  Index(['A', 'B', 'C'], dtype='object')
Index:  RangeIndex(start=0, stop=5, step=1)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

### DataFrames Applying Functions

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
def square(x):
  return x**2
df1['D']=df1['B'].apply(square) # apply accept a function
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

##Projects

### Features Extraction

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv(r'/content/anime.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: '/content/anime.csv'

#### Extract no. of episodes from data and make a new columns of episodes

In [ ]:
df['Title']

In [ ]:
def episode_extract(txt):
  data=""
  check=False
  for i in txt:
    if i==')':
      check=False
      break
    if i=='(':
     check=True
     continue
    if check==True:
      data+=i
  return data
df['episodes']=df['Title'].apply(episode_extract)
df['episode']=df['episode'].str.replace(" eps","")
df['episode']=df['episode'].astype(int)
df

#### Make a new column for time stamps

In [ ]:
df['Title'][1]
def time_stamps(txt):
  data=""
  for i in range(len(txt)):
    if txt[i]==')':
      for j in range(i+1,i+20):
        data+=txt[j]
  return data
  # calculating month count
def count_months(date_range):
    start, end = [x.strip() for x in date_range.split('-')]

    start = pd.to_datetime(start, format='%b %Y')
    end = pd.to_datetime(end, format='%b %Y')

    # Inclusive month count
    return (end.year - start.year) * 12 + (end.month - start.month) + 1
df['time_stamps']=df['Title'].apply(time_stamps) # time stamps
df['months_count']=df['time_stamps'].apply(count_months) # month count
df

#### countries extraction