<a href="https://colab.research.google.com/github/Adarsh230305/Data_Science/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [48]:
df=sns.load_dataset('titanic')

In [49]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [50]:
df.shape

(891, 15)

In [51]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [53]:
# droping useless data points
df.drop(["who",'adult_male','deck','alive','embark_town'],inplace=True,axis=1)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   class     891 non-null    category
 9   alone     891 non-null    bool
dtypes: bool(1), category(1), float64(2), int64(4), object(2)
memory usage: 57.7+ KB

In [55]:
df['age'].fillna(df['age'].mean(),inplace=True)

In [56]:
# Droping two null rows from embarked columns
df.dropna(subset=['embarked'],inplace=True)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   class     889 non-null    category
 9   alone     889 non-null    bool
dtypes: bool(1), category(1), float64(2), int64(4), object(2)
memory usage: 64.4+ KB

## Label Encoding

In [58]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cols=["sex",'embarked','class']
for x in cols:
  df[x]= le.fit_transform(df[x])
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,alone
0,0,3,1,22.000000,1,0,7.2500,2,2,False
1,1,1,0,38.000000,1,0,71.2833,0,0,False
2,1,3,0,26.000000,0,0,7.9250,2,2,True
3,1,1,0,35.000000,1,0,53.1000,2,0,False
4,0,3,1,35.000000,0,0,8.0500,2,2,True
...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,2,1,True
887,1,1,0,19.000000,0,0,30.0000,2,0,True
888,0,3,0,29.699118,1,2,23.4500,2,2,False
889,1,1,1,26.000000,0,0,30.0000,0,0,True
890,0,3,1,32.000000,0,0,7.7500,1,2,True

In [59]:
df['alone']=df['alone'].astype(int)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    int64
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    int64
 8   class     889 non-null    int64
 9   alone     889 non-null    int64
dtypes: float64(2), int64(8)
memory usage: 76.4 KB

In [61]:
x=df.drop('survived',axis=1)
y=df['survived']

In [62]:
# Train_test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#Models

## Logistic Regression Model

In [63]:
# logistic model
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [64]:
y_pred=model.predict(x_test)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

### Model evaluation

In [65]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [66]:
accuracy_score(y_test,y_pred)

0.8089887640449438

In [67]:
confusion_matrix(y_test,y_pred)

array([[91, 18],
       [16, 53]])

In [68]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.75      0.77      0.76        69

    accuracy                           0.81       178
   macro avg       0.80      0.80      0.80       178
weighted avg       0.81      0.81      0.81       178

## KNN Model

In [69]:
# first lets do feature scaling
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,alone
0,0,3,1,22.000000,1,0,7.2500,2,2,0
1,1,1,0,38.000000,1,0,71.2833,0,0,0
2,1,3,0,26.000000,0,0,7.9250,2,2,1
3,1,1,0,35.000000,1,0,53.1000,2,0,0
4,0,3,1,35.000000,0,0,8.0500,2,2,1
...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,2,1,1
887,1,1,0,19.000000,0,0,30.0000,2,0,1
888,0,3,0,29.699118,1,2,23.4500,2,2,0
889,1,1,1,26.000000,0,0,30.0000,0,0,1
890,0,3,1,32.000000,0,0,7.7500,1,2,1

In [70]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.fit_transform(x_test)

In [71]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train_scaled,y_train)
y_pred=knn_model.predict(x_test_scaled)

In [72]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,y_pred)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83       109
           1       0.73      0.75      0.74        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

In [73]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [17, 52]])

## Naive bayes model

In [74]:
from sklearn.naive_bayes import GaussianNB
model_nb=GaussianNB()
model_nb.fit(x_train,y_train)
y_pred_nb=model_nb.predict(x_test)

In [75]:
accuracy_score(y_test,y_pred_nb)

0.7528089887640449

In [76]:
confusion_matrix(y_test,y_pred_nb)

array([[81, 28],
       [16, 53]])

In [77]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83       109
           1       0.73      0.75      0.74        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

## Decision Tree Model

In [78]:
from sklearn.tree import DecisionTreeClassifier
model_dt=DecisionTreeClassifier()
model_dt.fit(x_train_scaled,y_train)
y_pred_dt=model_dt.predict(x_test_scaled)

In [79]:
accuracy_score(y_test,y_pred_dt)

0.6853932584269663

In [80]:
confusion_matrix(y_test,y_pred_dt)

array([[74, 35],
       [21, 48]])

In [81]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.78      0.68      0.73       109
           1       0.58      0.70      0.63        69

    accuracy                           0.69       178
   macro avg       0.68      0.69      0.68       178
weighted avg       0.70      0.69      0.69       178

## Support vector machine(SVM) model

In [82]:
from sklearn.svm import SVC
model_svm=SVC(kernel='rbf')
model_svm.fit(x_train_scaled,y_train)

SVC()

In [83]:
y_pred=model_svm.predict(x_test_scaled)

In [84]:
accuracy_score(y_test,y_pred)

0.8314606741573034

In [85]:
confusion_matrix(y_test,y_pred)

array([[96, 13],
       [17, 52]])

In [86]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.88      0.86       109
           1       0.80      0.75      0.78        69

    accuracy                           0.83       178
   macro avg       0.82      0.82      0.82       178
weighted avg       0.83      0.83      0.83       178

##K-fold cross validation

In [87]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,alone
0,0,3,1,22.000000,1,0,7.2500,2,2,0
1,1,1,0,38.000000,1,0,71.2833,0,0,0
2,1,3,0,26.000000,0,0,7.9250,2,2,1
3,1,1,0,35.000000,1,0,53.1000,2,0,0
4,0,3,1,35.000000,0,0,8.0500,2,2,1
...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,2,1,1
887,1,1,0,19.000000,0,0,30.0000,2,0,1
888,0,3,0,29.699118,1,2,23.4500,2,2,0
889,1,1,1,26.000000,0,0,30.0000,0,0,1
890,0,3,1,32.000000,0,0,7.7500,1,2,1

In [89]:
X=df.drop("survived",axis=1)
y=df['survived']

In [91]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [93]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(model_svm,X_scaled,y,cv=5,scoring="accuracy")
score

array([0.8258427 , 0.82022472, 0.82022472, 0.80898876, 0.86440678])

In [94]:
score.mean()

np.float64(0.8279375357074844)

##